# Generated by Django 2.0.7 on 2018-07-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField()),
                ('body', models.CharField(max_length=200)),
            ],
        ),
    ]
